/**
 * Locators for the OrangeHRM login screen.
 *
 * AUTO-GENERATED by scripts/fetch_locators.js from the live site.
 * Regenerate with:  npm run fetch:locators
 */
export const loginLocators = {
  usernameInput: "input[name=\"username\"]",
  passwordInput: "input[name=\"password\"]",
  loginButton: ".orangehrm-login-button",
  loginForm: ".orangehrm-login-form",
  error: ".orangehrm-login-error",
  title: ".orangehrm-login-title",
  logo: ".orangehrm-login-logo",
} as const;

/** Accessible-name based locators, useful when names are stable across builds. */
export const loginAriaLocators = {
  usernameLabel: 'Username',
  passwordLabel: 'Password',
  loginButtonLabel: 'Login',
} as const;
